FROM python:3.11-slim

WORKDIR /
RUN mkdir -p jobs/database-initializer
COPY requirements.txt .
COPY jobs/database-initializer /jobs/database-initializer

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "jobs/database-initializer/main.py"]
