FROM python:3.13-slim

WORKDIR /
RUN mkdir -p services/image_server

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/image_server /services/image_server

CMD ["uvicorn", "services.image_server.main:app", "--host", "0.0.0.0", "--port", "8000"]
