FROM python:3.13-slim

WORKDIR /
RUN mkdir -p app/task_master
RUN mkdir -p app/common

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/task_master /app/task_master
COPY app/common /app/common

WORKDIR /app

ENV PYTHONPATH=.

CMD ["uvicorn", "task_master.main:server", "--host", "0.0.0.0", "--port", "8000"]
