FROM python:3.13-slim

WORKDIR /
RUN mkdir -p services/user_manager

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/user_manager /services/user_manager

CMD ["uvicorn", "services.user_manager.main:app", "--host", "0.0.0.0", "--port", "8000"]
