FROM python:3.13-slim

WORKDIR /
RUN mkdir -p app/task_master

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/task_master /app/task_master

CMD ["uvicorn", "app.task_master.main:app", "--host", "0.0.0.0", "--port", "8000"]
