FROM python:3.13-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p app/worker
RUN mkdir -p app/common
COPY app/worker /app/worker
COPY app/common /app/common

WORKDIR /

ENV PYTHONPATH=.

CMD ["python", "app/worker/main.py"]
