FROM python:3.11-slim

WORKDIR /
RUN mkdir -p app/frontend
RUN mkdir -p app/common

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/frontend /app/frontend
COPY app/common /app/common

ENV PYTHONPATH=.

WORKDIR /app

# Command to run Streamlit
CMD ["python", "frontend/main.py"]
