apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server-deployment
  labels:
    app: image-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: image-server
    spec:
      containers:
        - name: image-server
          image: faas/image-server:0.0.1
          ports:
            - containerPort: 8000
