apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: faas/worker:0.0.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: volume-secret-credentials
              mountPath: "/etc/secret"
              readOnly: true
      volumes:
        - name: volume-secret-credentials
          secret:
            secretName: secret-credentials
