apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-master-deployment
  labels:
    app: task-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: task-master
    spec:
      containers:
        - name: task-master
          image: faas/task-master:0.0.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: volume-secret-credentials
              mountPath: "/etc/secret"
              readOnly: true
      volumes:
        - name: volume-secret-credentials
          secret:
            secretName: secret-credentials
