apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-deployment
  labels:
    app: user-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
        - name: user-manager
          image: fas/user-manager:0.0.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: volume-secret-credentials
              mountPath: "/etc/secret"
              readOnly: true
      volumes:
        - name: volume-secret-credentials
          secret:
            secretName: secret-credentials
